/**
 * The configuration of hexes in the Stolen Lands region map.
 * Format for the key is ROW.COL
 * @enum {Readonly<{}>}
 */
export default Object.freeze({
  '0.0': { zone: 'NA' },
  '0.1': { zone: 'NU' },
  '0.2': { zone: 'NU' },
  '0.3': { zone: 'NU' },
  '0.4': { zone: 'NU' },
  '0.5': { zone: 'NU' },
  '0.6': { zone: 'GU' },
  '0.7': { zone: 'GU' },
  '0.8': { zone: 'GU' },
  '0.9': { zone: 'TL' },
  '0.10': { zone: 'TL' },
  '0.11': { zone: 'TL' },
  '0.12': { zone: 'TL' },
  '0.13': { zone: 'HT', terrain: 'wetlands', travel: 'difficult' },
  '0.14': { zone: 'NM' },
  '0.15': { zone: 'NM' },
  '0.16': { zone: 'NM' },
  '0.17': { zone: 'NM' },
  '0.18': { zone: 'RL' },
  '0.19': { zone: 'RL' },
  '0.20': { zone: 'RL' },
  '0.21': { zone: 'RL' },
  '0.22': { zone: 'RL' },
  '0.23': { zone: 'RL' },
  '0.24': { zone: 'RL' },
  '0.25': { zone: 'BV' },
  '0.26': { zone: 'BV' },
  '0.27': { zone: 'BV' },
  '0.28': { zone: 'BV' },
  '0.29': { zone: 'BV' },
  '0.30': { zone: 'NA' },
  '1.0': { zone: 'NU' },
  '1.1': { zone: 'NU' },
  '1.2': { zone: 'NU' },
  '1.3': { zone: 'NU', discovery: 'landmark', terrain: 'hills', travel: 'difficult', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.Yi69pXvxHvRSntLD', state: {features: [{type: "landmark"}]}},
  '1.4': { zone: 'NU' },
  '1.5': { zone: 'GU' },
  '1.6': { zone: 'GU' },
  '1.7': { zone: 'GU' },
  '1.8': { zone: 'TL', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.RMr4ocSxco9r9RQT', state: {commodity: "ore"} },
  '1.9': { zone: 'TL', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.eJL22j72xd9TxXKB', state: {features: [{type: "refuge"}]}},
  '1.10': { zone: 'TL' },
  '1.11': { zone: 'TL' },
  '1.12': { zone: 'HT', discovery: 'landmark', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.bG1yUiHIe8jQodWn', state: {features: [{type: "bridge"}]} },
  '1.13': { zone: 'NM' },
  '1.14': { zone: 'NM' },
  '1.15': { zone: 'NM', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.yWv3iZpCAHZYyeBL' },
  '1.16': { zone: 'NM' },
  '1.17': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.kVVUA8clBkwioljc' },
  '1.18': { zone: 'RL' },
  '1.19': { zone: 'RL', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.4OzzzKtfhPKmGFR5', state: {features: [{type: "refuge"}, {type: "structure", name: "General Store"}]}},
  '1.20': { zone: 'RL' },
  '1.21': { zone: 'RL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.NSCPFMAAUkbqCpsv', state: {features: [{type: "structure", name: "Alchemy Laboratory"}]}},
  '1.22': { zone: 'RL' },
  '1.23': { zone: 'RL', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.QZiCe0AM0B1fMEeo' },
  '1.24': { zone: 'RL' },
  '1.25': { zone: 'BV', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.TAWfHVA0XQ4uZSDN', state: { features: [{type: "village", name: "CN Village 1", discovered: true}, {type: "bridge", discovered: true}]}},
  '1.26': { zone: 'BV' },
  '1.27': { zone: 'BV', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.oKK8LQSTWgtMuTdt', state: {exploration: 1, features: [{type: "city", name: "CN City 9", discovered: true}, {type: "bridge", discovered: true}]}},
  '1.28': { zone: 'BV' },
  '1.29': { zone: 'NA' },
  '1.30': { zone: 'NA' },
  '2.0': { zone: 'NA' },
  '2.1': { zone: 'NU' },
  '2.2': { zone: 'NU' },
  '2.3': { zone: 'BR' },
  '2.4': { zone: 'BR' },
  '2.5': { zone: 'GU', terrain: 'mountains', travel: 'difficult' },
  '2.6': { zone: 'GU', discovery: 'landmark', terrain: 'hills', travel: 'difficult', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.bqajH1Ldk27EF6p9' },
  '2.7': { zone: 'GU' },
  '2.8': { zone: 'GU' },
  '2.9': { zone: 'TL' },
  '2.10': { zone: 'TL', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.7XdF3dBhWlBm7swV', state: {features: [{type: "refuge"}]}},
  '2.11': { zone: 'TL' },
  '2.12': { zone: 'HT', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.EaFnSYocKQ7aN63k' },
  '2.13': { zone: 'HT', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.S2t8E7q19qoQMUD2' },
  '2.14': { zone: 'NM' },
  '2.15': { zone: 'NM' },
  '2.16': { zone: 'NM' },
  '2.17': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.u82N7BlDpCf1FCD9' },
  '2.18': { zone: 'GB', discovery: 'secret', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.2bPpvW64EVxVnBNS' },
  '2.19': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.0lvPsH4bhauRLQiW' },
  '2.20': { zone: 'RL' },
  '2.21': { zone: 'RL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.pu7jESDH8f14oUCD' },
  '2.22': { zone: 'RL' },
  '2.23': { zone: 'RL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.KBMmaiMrbRl1rq8N', state: {features: [{type: "structure", name: "Barracks"}]}},
  '2.24': { zone: 'RL', terrain: 'hills', travel: 'open' },
  '2.25': { zone: 'RL', discovery: 'secret', terrain: 'hills', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.C7DPXkLktqOFKfS2' },
  '2.26': { zone: 'DS' },
  '2.27': { zone: 'DS' },
  '2.28': { zone: 'DS', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.TZIBWIBPRj8yEsWO' },
  '2.29': { zone: 'DS' },
  '2.30': { zone: 'NA' },
  '3.0': { zone: 'BR' },
  '3.1': { zone: 'BR' },
  '3.2': { zone: 'BR' },
  '3.3': { zone: 'BR', discovery: 'landmark', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.h0o21qoIu5WMGoYr' },
  '3.4': { zone: 'GU', discovery: 'landmark', terrain: 'hills', travel: 'difficult', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.fnBr26RvgXnMKxXu', state: {features: [{type: "refuge"}, {type: "structure", name: "Temple, Brewery"}]}},
  '3.5': { zone: 'GU', terrain: 'hills', travel: 'difficult' },
  '3.6': { zone: 'GU', terrain: 'hills', travel: 'difficult' },
  '3.7': { zone: 'GU' },
  '3.8': { zone: 'TL', discovery: 'secret', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.hRKjFKLQ5LmAIOEw' },
  '3.9': { zone: 'TL', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.vG9iqIGagYz1iLkk' },
  '3.10': { zone: 'TL', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.MahW1XszWOVet9Rc' },
  '3.11': { zone: 'HT' },
  '3.12': { zone: 'HT' },
  '3.13': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.6BR5MvbUKEdXkJyI' },
  '3.14': { zone: 'NM' },
  '3.15': { zone: 'NM' },
  '3.16': { zone: 'GB', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.KcFCO4CagRfIal7b' },
  '3.17': { zone: 'GB', discovery: 'secret', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.ZyMSUFOBkSXlRhmM', state: {features: [{type: "refuge"}, {type: "structure", name: "Shrine"}]}},
  '3.18': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.PshoqiPZaqVe6eva' },
  '3.19': { zone: 'GB', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.ubo7wSHGwDt3exrb', state: {commodity: "ore"} },
  '3.20': { zone: 'GB', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.Wx7xVpuvBjZC85RJ' },
  '3.21': { zone: 'GB' },
  '3.22': { zone: 'GB', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.22954zATDfyxUfqF' },
  '3.23': { zone: 'KL' },
  '3.24': { zone: 'DS', discovery: 'standard', terrain: 'mountains', travel: 'difficult', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.uhxRXGBx6TUOUenv' },
  '3.25': { zone: 'DS', discovery: 'landmark', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.xa16q1JiEKDE0XvX', state: {features: [{type: "bridge"}]}},
  '3.26': { zone: 'DS', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.YVZA2hTSonCuThYw' },
  '3.27': { zone: 'DS' },
  '3.28': { zone: 'DS' },
  '3.29': { zone: 'NA' },
  '3.30': { zone: 'NA' },
  '4.0': { zone: 'NA' },
  '4.1': { zone: 'BR' },
  '4.2': { zone: 'BR', discovery: 'landmark', terrain: 'swamp', travel: 'greater', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.uNAAUKpgGkFOuL7Q' },
  '4.3': { zone: 'BR', discovery: 'standard', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.ziXfEypGrwls4L0M', state: {features: [{type: "refuge"}]}},
  '4.4': { zone: 'GU' },
  '4.5': { zone: 'GU', terrain: 'hills', travel: 'difficult' },
  '4.6': { zone: 'GU', terrain: 'hills', travel: 'difficult' },
  '4.7': { zone: 'GL' },
  '4.8': { zone: 'GL' },
  '4.9': { zone: 'TL' },
  '4.10': { zone: 'DR', discovery: 'secret', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.fGryMMXxWm8R3fqw' },
  '4.11': { zone: 'HT' },
  '4.12': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.yCPnwYenBJkYftSt' },
  '4.13': { zone: 'HT', terrain: 'lake', travel: 'water' },
  '4.14': { zone: 'HT' },
  '4.15': { zone: 'NM' },
  '4.16': { zone: 'NM', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.FaEGQyzM1OWCNePT', state: {features: [{type: "structure", name: "Monument"}]}},
  '4.17': { zone: 'GB', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.6JPqGqeYHNastNOd', state: {features: [{type: "refuge"}, {type: "structure", name: "Houses"}]}},
  '4.18': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.x20Bq8Uu3Lgo0QIM' },
  '4.19': { zone: 'GB', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.Yg00bRg7Bu4aB6lj' },
  '4.20': { zone: 'GB', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.ZMiq3a0Iy6iUl3Cc', state: {features: [{type: "bridge"}]}},
  '4.21': { zone: 'GB', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.EWskVd3XK5UjNWyD' },
  '4.22': { zone: 'GB' },
  '4.23': { zone: 'KL' },
  '4.24': { zone: 'LV', discovery: 'landmark', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.V8MIjPmcNKIR14MK', state: {features: [{type: "structure", name: "Watchtower"}]}},
  '4.25': { zone: 'DS', discovery: 'landmark', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.qpjnkUuNhEKbwFmX', state: {features: [{type: "town", name: "NG Town 5"}]}},
  '4.26': { zone: 'DS' },
  '4.27': { zone: 'DS', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.eLR67Cq1aAMrGvmz' },
  '4.28': { zone: 'DS' },
  '4.29': { zone: 'DS' },
  '4.30': { zone: 'NA' },
  '5.0': { zone: 'TV' },
  '5.1': { zone: 'TV', discovery: 'secret', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.rRpbmn5PXfDOTiy9' },
  '5.2': { zone: 'TV' },
  '5.3': { zone: 'GU', discovery: 'secret', terrain: 'hills', travel: 'greater', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.mcFHAum0dL4gnn2b' },
  '5.4': { zone: 'GU' },
  '5.5': { zone: 'GL', discovery: 'standard', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.O8cuvFXBUssLzK03' },
  '5.6': { zone: 'GL' },
  '5.7': { zone: 'GL' },
  '5.8': { zone: 'TL' },
  '5.9': { zone: 'DR' },
  '5.10': { zone: 'DR', discovery: 'landmark', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.82mZBGmsRLZhZ0ky', state: {features: [{type: "town", name: "NE Town 3"}]}},
  '5.11': { zone: 'HT', discovery: 'landmark', terrain: 'lake', travel: 'water', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.F2jziCo01RR37QUd', state: {features: [{type: "freehold"}]}},
  '5.12': { zone: 'HT', discovery: 'landmark', terrain: 'lake', travel: 'water', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.40NQKLd87xjuW29A', state: {features: [{type: "landmark"}]}},
  '5.13': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.7KGT3UyIuOgkre6N' },
  '5.14': { zone: 'NM' },
  '5.15': { zone: 'NM', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.bMv7GhCTSKwob3w7' },
  '5.16': { zone: 'GB', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.TUUvCrADHplbc1pa' },
  '5.17': { zone: 'GB', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.ml2PZxAUYY9XRXOJ' },
  '5.18': { zone: 'GB', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.gchJ4zee0YurJdM9' },
  '5.19': { zone: 'GB', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.Lj2an3QQ4vrtgTqR' },
  '5.20': { zone: 'GB', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.TVuBzJOfoiGT46dS', state: {commodity: "ore"} },
  '5.21': { zone: 'KL' },
  '5.22': { zone: 'KL' },
  '5.23': { zone: 'LV', discovery: 'landmark', terrain: 'mountains', travel: 'greater', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.R2lMe31957wfLbAN', state: {features: [{type: "ruin", name: "Ruined Watchtower"}]}},
  '5.24': { zone: 'LV', discovery: 'secret', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.GIwu0CRXdB8hXGbC', state: {features: [{type: "refuge"}]}},
  '5.25': { zone: 'LV' },
  '5.26': { zone: 'NH' },
  '5.27': { zone: 'NH', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.imV3SGNZPib6Qajt' },
  '5.28': { zone: 'NH' },
  '5.29': { zone: 'NA' },
  '5.30': { zone: 'NA' },
  '6.0': { zone: 'NA' },
  '6.1': { zone: 'TV' },
  '6.2': { zone: 'TV' },
  '6.3': { zone: 'TV' },
  '6.4': { zone: 'GU' },
  '6.5': { zone: 'GL' },
  '6.6': { zone: 'GL' },
  '6.7': { zone: 'GL', discovery: 'standard', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.vwy930AkMwsvWYvO' },
  '6.8': { zone: 'RU' },
  '6.9': { zone: 'DR', terrain: 'forest', travel: 'open' },
  '6.10': { zone: 'DR' },
  '6.11': { zone: 'HT' },
  '6.12': { zone: 'HT' },
  '6.13': { zone: 'HT', discovery: 'landmark', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.5mmKhhH0wt7aDMFY' },
  '6.14': { zone: 'NM', discovery: 'landmark', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.BnsFiKH1vb8eYOFo' },
  '6.15': { zone: 'NM' },
  '6.16': { zone: 'KL', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.bLxVZCuHjKPssNXv', state: {features: [{type: "refuge"}]}},
  '6.17': { zone: 'TW', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.xV79hESaQK18sFqC' },
  '6.18': { zone: 'TW', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.VbsfXQwW3j5ewHah' },
  '6.19': { zone: 'TW', discovery: 'landmark', terrain: 'hills', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.rfqqwXigGo3EVybY', state: {features: [{type: "structure", name: "Town Hall"}]}},
  '6.20': { zone: 'TW', discovery: 'standard', terrain: 'hills', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.KHuglqqCu3m2Oo0I' },
  '6.21': { zone: 'TW', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.0KcdmwGleIUTokCO', state: {features: [{type: "refuge"}]}},
  '6.22': { zone: 'KL' },
  '6.23': { zone: 'KL' },
  '6.24': { zone: 'KL', discovery: 'standard', terrain: 'wetlands', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.Iuu10Vi4hlfM2ejd' },
  '6.25': { zone: 'LV' },
  '6.26': { zone: 'NH' },
  '6.27': { zone: 'NH', discovery: 'landmark', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.OiJ10buS4REiy44M' },
  '6.28': { zone: 'NH' },
  '6.29': { zone: 'NH' },
  '6.30': { zone: 'NA' },
  '7.0': { zone: 'TV' },
  '7.1': { zone: 'TV' },
  '7.2': { zone: 'TV' },
  '7.3': { zone: 'PX', discovery: 'landmark', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.royVC8UEgzrekNYI', state: {features: [{type: "village", name: "LN Village 2"}, {type: "ruin", name:"Ruined Houses, Ruined General Store, Ruined Town Hall"}]}},
  '7.4': { zone: 'GL' },
  '7.5': { zone: 'GL' },
  '7.6': { zone: 'RU', discovery: 'landmark', terrain: 'lake', travel: 'water', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.AfZlGU0YdF4Ct4og' },
  '7.7': { zone: 'RU' },
  '7.8': { zone: 'DR', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.IJsHt4PfMQ1EDbxc' },
  '7.9': { zone: 'DR', terrain: 'forest', travel: 'open' },
  '7.10': { zone: 'HT' },
  '7.11': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.3sEYrHgRPKVbEyc3' },
  '7.12': { zone: 'HT' },
  '7.13': { zone: 'NM' },
  '7.14': { zone: 'NM' },
  '7.15': { zone: 'NM', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.HD0KAGBGF1eUoAw8', state: {features: [{type: "ruin", name:"Ruined Castle"}]}},
  '7.16': { zone: 'KL', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.74j7323OPObRW94u' },
  '7.17': { zone: 'TW', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.XVAPsU3tc3i5rS2j' },
  '7.18': { zone: 'TW', discovery: 'standard', terrain: 'wetlands', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.kB6Hr2406re5HjuL', state: {features: [{type: "structure", name:"Herbalist"}]}},
  '7.19': { zone: 'TW', discovery: 'secret', terrain: 'hills', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.eiumBclzypz1cuWy' },
  '7.20': { zone: 'TW', discovery: 'landmark', terrain: 'hills', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.SgWg7pNQK1RK68V3' },
  '7.21': { zone: 'KL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.fOWc0zSSohUTKxnN', state: {features: [{type: "refuge"}, {type: "structure", name: "Popular Tavern"}]}},
  '7.22': { zone: 'KL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.SCbb3uIL4P5qzSD1' },
  '7.23': { zone: 'KL', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.0tz4d6qKT885s0hZ' },
  '7.24': { zone: 'LV' },
  '7.25': { zone: 'LV', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.rtOFQVGvsJUNumiq' },
  '7.26': { zone: 'NH' },
  '7.27': { zone: 'NH' },
  '7.28': { zone: 'NH' },
  '7.29': { zone: 'NA' },
  '7.30': { zone: 'NA' },
  '8.0': { zone: 'NA' },
  '8.1': { zone: 'TV' },
  '8.2': { zone: 'TV', discovery: 'standard', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.CIyIRUrYVPCvVPXL' },
  '8.3': { zone: 'PX', terrain: 'forest', travel: 'open' },
  '8.4': { zone: 'PX' },
  '8.5': { zone: 'GL' },
  '8.6': { zone: 'RU', discovery: 'landmark', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.mAebEUoHT3KIVboK', state: {features: [{type: "structure", name: "Cistern, Houses"}]}},
  '8.7': { zone: 'RU', discovery: 'standard', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.GMOsLUes0rbLNRBv' },
  '8.8': { zone: 'RU' },
  '8.9': { zone: 'DR' },
  '8.10': { zone: 'HT' },
  '8.11': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.ZR78OnzaOJ4fEOmc' },
  '8.12': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.T9E2dW6t7Ys88EFr' },
  '8.13': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.TPQzLBZNh8uAxb0X' },
  '8.14': { zone: 'NM' },
  '8.15': { zone: 'NM', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.UNIuaL8dodRaKkU1' },
  '8.16': { zone: 'NM' },
  '8.17': { zone: 'KL', discovery: 'landmark', terrain: 'wetlands', travel: 'open', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.dqCbC2C5XlKMdbrm', state: {features: [{type: "freehold"}, {type: "structure", name: "Barracks, Houses, Shrine, Wooden Walls"}]}},
  '8.18': { zone: 'KL', discovery: 'landmark', terrain: 'lake', travel: 'water', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.fraqnPjBmnq2ToHs', state: {features: [{type: "refuge"}, {type: "structure", name: "Watchtower"}]}},
  '8.19': { zone: 'KL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.WZB1k6alpwK5lu24' },
  '8.20': { zone: 'KL' },
  '8.21': { zone: 'KL', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.vyx7CWwaPUuRQwNe' },
  '8.22': { zone: 'KL' },
  '8.23': { zone: 'KL' },
  '8.24': { zone: 'SH', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.qP7ktIfPJlSP4ZRZ' },
  '8.25': { zone: 'LV', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.6n26fPq0yA0wGXmv', state: {commodity: "ore"} },
  '8.26': { zone: 'LV', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.LKXR6bDtNenHkRNu', state: {features: [{type: "refuge"}]}},
  '8.27': { zone: 'LV', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.Ifkaf0EzRomzvfqw' },
  '8.28': { zone: 'LV' },
  '8.29': { zone: 'LV' },
  '8.30': { zone: 'NA' },
  '9.0': { zone: 'PX', terrain: 'forest', travel: 'open' },
  '9.1': { zone: 'PX', terrain: 'forest', travel: 'open' },
  '9.2': { zone: 'PX', terrain: 'forest', travel: 'open' },
  '9.3': { zone: 'PX' },
  '9.4': { zone: 'PX' },
  '9.5': { zone: 'PX', discovery: 'landmark', page: 'JournalEntry.btt2UVnNmyuPWfHF.JournalEntryPage.GEZajnLpmkBcqsjb', state: { features: [{type: "city", name: "CN City 10"}, {type: "bridge"}, {type: "structure", name: "Houses (x9), Alchemy Lab, Barracks, Illicit Market, Cathedral, Graveyard, Guildhall, Inn, Palace, Popular Tavern, Secure Warehouse, Shrine, Specialised Artisan (x2), Theater, Waterfront"}]}},
  '9.6': { zone: 'RU' },
  '9.7': { zone: 'RU' },
  '9.8': { zone: 'DR' },
  '9.9': { zone: 'DR', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.FXt4alYXXGVfNQSE' },
  '9.10': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.hbhsH1QAIVKJRv51' },
  '9.11': { zone: 'HT' },
  '9.12': { zone: 'HT', discovery: 'standard', page: 'JournalEntry.GRbTr3VTyhezOEhW.JournalEntryPage.05BaUXEK37R4F93t' },
  '9.13': { zone: 'HT' },
  '9.14': { zone: 'NM' },
  '9.15': { zone: 'NM', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.JA4V2iDJug2ZAaRo', state: {features: [{type: "refuge"}]}},
  '9.16': { zone: 'SH', discovery: 'standard', terrain: 'forest', travel: 'difficult', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.GigD9Vk2ZHOCYQch' },
  '9.17': { zone: 'SH', terrain: 'forest', travel: 'difficult' },
  '9.18': { zone: 'SH', discovery: 'standard', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.xbpbUAxWHcsX1g6Q' },
  '9.19': { zone: 'SH', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.dTuvqi5n5EBNGikQ', state: {features: [{type: "structure", name: "Pier"}]}},
  '9.20': { zone: 'SH', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.89NaJI7jtOsnTr9K', state: {features: [{type: "refuge"}]}},
  '9.21': { zone: 'SH' },
  '9.22': { zone: 'SH', discovery: 'landmark', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.6XedadsboOVoVr1z', state: {features: [{type: "freehold"}, {type: "structure", name: "Alchemy Lab, Shrine, Stables, Tenements, Wooden Walls"}]}},
  '9.23': { zone: 'SH', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.mTd4ffC2vFhOnPXW', state: {commodity: "luxuries"} },
  '9.24': { zone: 'SH', discovery: 'secret', page: 'JournalEntry.5QajqjVS7Dm8u7hi.JournalEntryPage.x9akvOBdMxgcO2xg', state: {features: [{type: "refuge"}]}},
  '9.25': { zone: 'LV' },
  '9.26': { zone: 'LV' },
  '9.27': { zone: 'LV', discovery: 'standard', page: 'JournalEntry.lMIawppop9uCHRXq.JournalEntryPage.SzMLdjJzB4R65Ux0', state: {features: [{type: "refuge"}]}},
  '9.28': { zone: 'LV' },
  '9.29': { zone: 'NA' },
  '9.30': { zone: 'NA' },
  '10.0': { zone: 'NA' },
  '10.1': { zone: 'PX' },
  '10.2': { zone: 'PX' },
  '10.3': { zone: 'PX' },
  '10.4': { zone: 'PX' },
  '10.5': { zone: 'PX' },
  '10.6': { zone: 'RU' },
  '10.7': { zone: 'RU' },
  '10.8': { zone: 'DR' },
  '10.9': { zone: 'DR' },
  '10.10': { zone: 'HT' },
  '10.11': { zone: 'HT' },
  '10.12': { zone: 'HT' },
  '10.13': { zone: 'HT' },
  '10.14': { zone: 'NM' },
  '10.15': { zone: 'NM' },
  '10.16': { zone: 'NM' },
  '10.17': { zone: 'SH', terrain: 'forest', travel: 'difficult' },
  '10.18': { zone: 'SH' },
  '10.19': { zone: 'SH' },
  '10.20': { zone: 'SH' },
  '10.21': { zone: 'SH' },
  '10.22': { zone: 'SH' },
  '10.23': { zone: 'SH' },
  '10.24': { zone: 'SH' },
  '10.25': { zone: 'SH' },
  '10.26': { zone: 'LV' },
  '10.27': { zone: 'LV' },
  '10.28': { zone: 'LV' },
  '10.29': { zone: 'LV' },
  '10.30': { zone: 'NA' },
  '11.0': { zone: 'NA' },
  '11.1': { zone: 'NA' },
  '11.2': { zone: 'NA' },
  '11.3': { zone: 'NA' },
  '11.4': { zone: 'NA' },
  '11.5': { zone: 'NA' },
  '11.6': { zone: 'NA' },
  '11.7': { zone: 'NA' },
  '11.8': { zone: 'NA' },
  '11.9': { zone: 'NA' },
  '11.10': { zone: 'NA' },
  '11.11': { zone: 'NA' },
  '11.12': { zone: 'NA' },
  '11.13': { zone: 'NA' },
  '11.14': { zone: 'NA' },
  '11.15': { zone: 'NA' },
  '11.16': { zone: 'NA' },
  '11.17': { zone: 'NA' },
  '11.18': { zone: 'NA' },
  '11.19': { zone: 'NA' },
  '11.20': { zone: 'NA' },
  '11.21': { zone: 'NA' },
  '11.22': { zone: 'NA' },
  '11.23': { zone: 'NA' },
  '11.24': { zone: 'NA' },
  '11.25': { zone: 'NA' },
  '11.26': { zone: 'NA' },
  '11.27': { zone: 'NA' },
  '11.28': { zone: 'NA' },
  '11.29': { zone: 'NA' },
  '11.30': { zone: 'NA' }
});
